version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped